all:
	echo running makefile
	sudo apt-get update
	-sudo apt-get install python3 python3-pip
	-sudo python3 -m pip install --user virtualenv
	-. /venv/bin/activate 
	-pip install -r requirements.txt
